### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by GermanGeraskin** [horgh/videostreamer#11]
Hi.
I am very new in software developers world, and I have never used golang before.
So, please excuse me. Could you, please, help me resolve this issue?

(the problem)
$  go get github.com/horgh/videostreamer
 github.com/horgh/videostreamer
/usr/bin/ld: /usr/local/lib/libavcodec.a(cuviddec.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
 github.com/horgh/videostreamer
videostreamer.c: In function ‘vs_setup’:
videostreamer.c:29:2: warning: ‘av_register_all’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:2025) [-Wdeprecated-declarations]
  av_register_all();
  ^

(additional info)
OS:   Linux  4.4.0-128-generic #154~14.04.1-Ubuntu 

ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
configuration: --fatal-warnings --enable-gpl --enable-nonfree --enable-version3 --enable-postproc --disable-w32threads --enable-pthreads --enable-avfilter --enable-libx264 --enable-nvenc --enable-decklink --extra-ldflags=-ldl --extra-libs=-ldl --extra-cflags=-I/usr/include/DeckLink --enable-ffplay --enable-openssl
libavutil      56. 14.100 / 56. 14.100
libavcodec     58. 18.100 / 58. 18.100
libavformat    58. 12.100 / 58. 12.100
libavdevice    58.  3.100 / 58.  3.100
libavfilter     7. 16.100 /  7. 16.100
libswscale      5.  1.100 /  5.  1.100
libswresample   3.  1.100 /  3.  1.100
libpostproc    55.  1.100 / 55.  1.100

**Comment by horgh** [comment]
Weird. It sort of looks like you may have a libavcodec installed that isn't working properly. It's in /usr/local so it's probably not one from the Ubuntu packages.

I'm not sure what to suggest. I'd probably try to get rid of that installation myself and rely on the packaged version. Although the version in 14.04 is too old to work with videostreamer. You'd need to use a newer Ubuntu release to get it. And that assumes you are able to clean up the install in /usr/local.

That's my best guess anyway. Sorry I can't be more help!

**Comment by GermanGeraskin** [comment]
Thank you very much for your response.

Yes. I believe /usr/local/lib/libavcodec.a is a part of ffmpeg installation (after building from sources).
But, there are some other versions installed from Ubuntu packages (I guess):

apt list --installed libavcodec*
libavcodec-dev/trusty-updates,trusty-security,now 6:9.20-0ubuntu0.14.04.1 amd64 [installed,automatic]
libavcodec54/trusty-updates,trusty-security,now 6:9.20-0ubuntu0.14.04.1 amd64 [installed,automatic]

Is it possible to build the videostreamer using libraries from ffmpeg sources?

**Comment by horgh** [comment]
Yeah, it should be possible. I just tried it on Ubuntu Trusty with ffmpeg 4.0.2 installed from source and it worked once I made a change in `videostreamer.go`:

```
-// #cgo LDFLAGS: -lavformat -lavdevice -lavcodec -lavutil
+// #cgo LDFLAGS: -lavformat -lavdevice -lavcodec -lavutil -lavfilter -lswscale
```

However I didn't see the error you showed. I'm not sure why. Maybe something else is different with your system.

You could try adding `-ldl` to the end of that line in `videostreamer.go` and then building.

**Comment by amonhuang** [comment]
I also got compile error:

> collect2: error: ld returned 1 exit status
...
videostreamer.c: In function ‘vs_setup’:
videostreamer.c:29:2: warning: ‘av_register_all’ is deprecated [-Wdeprecated-declarations]
  av_register_all();
  ^
In file included from /usr/local/include/libavdevice/avdevice.h:51:0,
                 from videostreamer.c:12:
/usr/local/include/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^

Here is my enviroment:
OS: 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 GNU/Linux
FFMPEG Version: 4.0.2
GO Version: 1.11

**Comment by horgh** [comment]
If you make the change I made in my prior comment, does that change anything?

Is there anything more shown? I think there may be more that's relevant.
