### ISSUE TITLE
Improve - How to reduce lag

### ISSUE THREAD

**Issue by juvasquezg** [horgh/videostreamer#2]
Hi,

Excuse me!!

I don't know if is by the client (<video> tag) or the server http but the lag is big.

How can I improve to reduce lag? 

Maybe 

- client and server using Websockets?

Thank you so much!!

**Comment by juvasquezg** [comment]
Hi,

Read this [stackoverflow](http://stackoverflow.com/questions/21921790/best-approach-to-real-time-http-streaming-to-html5-video-client)

Work similar but with other ffmpeg process.

Read [gist](https://gist.github.com/deandob/9240090)  set 

```bash
   res.writeHead(200, {
        //'Transfer-Encoding': 'binary'
          "Connection": "keep-alive"
        , "Content-Type": "video/mp4"
        //, 'Content-Length': chunksize            // ends after all bytes delivered
        , "Accept-Ranges": "bytes"                 // Helps Chrome
    });
```

and ffmpeg with 

```js
  let ffmpeg = spawn("ffmpeg", [
    "-rtsp_transport", "udp",
    "-i", "rtsp://admin:@192.168.0.109:554/live1.sdp",
    "-vcodec", "copy",
    "-f", "mp4",
    "-movflags", "frag_keyframe+empty_moov", 
    "-reset_timestamps", "1",
    "-vsync", "1",
    "-flags", "global_header",
    "-bsf:v", "dump_extra",
    "-y", "-" // output to stdout
  ],  { detached: false })
```

pipe to response client 

```js
ffmpeg.stdout.pipe(res)
```

Work with audio and the lag is not so big.

In nodejs run with 

```js
// index.js
'use strict'

const http = require('http')
const fs = require('fs')
const path = require('path')
const port = process.env.PORT || 8080
const spawn = require('child_process').spawn

const server = http.createServer()

server.on('request', onRequest)
server.on('listening', onListening)

server.listen(port)

function onRequest (req, res) {
  console.log("onRequest")

  res.writeHead(200, {
    //'Transfer-Encoding': 'binary'
    "Connection": "keep-alive",
    "Content-Type": "video/mp4",
    //'Content-Length': "chunksize",            // ends after all bytes delivered
    "Accept-Ranges": "bytes"                 // Helps Chrome
  });

  let ffmpeg = spawn("ffmpeg", [
    "-rtsp_transport", "udp",
    "-i", "rtsp://admin:@192.168.0.109:554/live1.sdp",
    "-vcodec", "copy",
    "-f", "mp4",
    "-movflags", "frag_keyframe+empty_moov", 
    "-reset_timestamps", "1",
    "-vsync", "1",
    "-flags", "global_header",
    "-bsf:v", "dump_extra",
    "-y", "-" // output to stdout
  ],  { detached: false })
  
  //rs.pipe(res)
  ffmpeg.stdout.pipe(res)

  ffmpeg.on("exit", function (code) {
    console.log("live FFMPEG terminated with code " + code);
  });

  ffmpeg.on("error", function (e) {
    console.log(" live FFMPEG system error: " + e);
  });


  rs.on('error', function (err) {
    res.setHeader('Content-Type', 'text/plain')
    res.end(err.message)
  })
}

function onListening () {
  console.log('Server running in port ' + port)
}
```

```bash
node index.js
```

Thank you so much!!!

**Comment by horgh** [comment]
Hi @juvasquezg!

That's unfortunate it is lagging. Can you tell me any more about how to see the problem? For example, does it start lagging only after a period of time? Or does it start happening almost right away?

Is there a stream you have I could test with to see the problem?

I don't know if this will be relevant, but what browser are you using?

The gist you show has several ffmpeg options that aren't used by videostreamer right now. I wonder if one of them is what is helping reduce the lag. One thing we can do is try adding them to videostreamer, and see if that helps.

Also we can try adjusting the HTTP headers to match as in the node.js example. Accept-Ranges is one to try.

If you can give me a stream to test with, I can see what I can figure out. If not I will try to find one and reproduce it.

**Comment by juvasquezg** [comment]
Hi @horgh , 

Thank you, in this moment the public url is **rtsp://admin:@181.143.83.131:554/live1.sdp** I run the command

```bash
./videostreamer -input=rtsp://admin:@181.143.83.131:554/live1.sdp -host=0.0.0.0 -port=8080 -format=rtsp -f cgi=false
```

It is a D-LINK DCS-2103 camera.

The output is

```bash
unable to write frame
2017/04/03 09:26:02 Failure writing packet
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
2017/04/03 09:26:03 Client too slow
unable to write trailer
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 4 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 7 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 6 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 3 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
2017/04/03 09:27:00 Serving [GET] request from [192.168.8.100:54737] to path [/] (0 bytes)
2017/04/03 09:27:00 Serving [GET] request from [192.168.8.100:54737] to path [/stream] (0 bytes)
2017/04/03 09:27:00 Opened output for client
2017/04/03 09:27:01 192.168.8.100:54606: Write error: write tcp 192.168.8.101:8080->192.168.8.100:54606: write: broken pipe
2017/04/03 09:27:01 192.168.8.100:54606: Client cleaned up
unable to write frame
2017/04/03 09:27:02 Failure writing packet
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
2017/04/03 09:27:03 Client too slow
unable to write trailer
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 2 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 2 packets
[rtsp @ 0x23f1420] max delay reached. need to consume packet
[rtsp @ 0x23f1420] RTP: missed 1 packets
```

Other problem is when I change the tab browser (stop video).

Thank you so much for your help.

**Comment by horgh** [comment]
Hi @juvasquezg 

Sorry for the delay, I've been pretty busy! I will look at this on the weekend.

**Comment by horgh** [comment]
Thanks for providing that log and the endpoint to test with! I am not sure why this is happening yet, but I've examined your log and tried to reproduce the problem.

I made one commit to add a bit more log output, and I have a couple questions.

Here is what I see:

Interestingly when I test with the endpoint, my client (in Firefox) can continue to watch the stream without getting cut off, and appears to be about realtime. I did see one notice like in your log:

```
2017/04/08 15:47:34 Opened output for client
[rtsp @ 0x7f91b8000b60] max delay reached. need to consume packet
[rtsp @ 0x7f91b8000b60] RTP: missed 1 packets
```

But it seems to have recovered. I see only one.

I'm looking at your log:

One thing I see is this "unable to write frame" error. This means for some reason, writing to the client's output failed. I see for the second client in your log, this happens after losing the HTTP connection to the client, so maybe that happened in both cases. It's possible that if there is a different reason that there could be something else going on though. I committed a change to report the reason.

Regardless, the program should continue to read packets from the input regardless of whether clients are misbehaving/being too slow/get lost. The notices about missing packets/max delay make me think there is a bug in that, such as keeping the input open without reading any frames from the input.

Does the problem start occurring only when you start having multiple clients? Or does it happen with just one? Would you be able to show a full log with just a single client where it happens, and with `-verbose` enabled too?

Regarding the issue you mentioned about stopping video when changing tabs, I think that might be able to be dealt with in JavaScript. Either way, I suggest we try to figure out the missing packets issue first, then look at that one.

To try to rule out any browser weirdness, you could also try downloading the stream with curl and see if the issue still happens. Something like this:

```
will@snorri:~/t$ curl -v http://0.0.0.0:8080/stream > out.mp4
```

I'll see if I can figure out how to use some of the other ffmpeg options you showed in your prior comment, so we can see if they make any difference for you.

**Comment by juvasquezg** [comment]
Hi @horgh

Thank you, Tomorrow I will test the changes.

Regards,
Julián

**Comment by juvasquezg** [comment]
Hi @horgh 

I tested with two clients (Chrome and Firefox). 

With Firefox work fine.

With Chrome, load the video tag and show only  from 2 to 10 seconds of video and stop it.

The Golang program continue and normal stdoutput

```bash
skipping packet from input stream 1, our video is from stream 0
in: pts:1338590 pts_time:14.8732 dts:1338590 dts_time:14.8732 duration:1200 duration_time:0.0133333 stream_index:0
out: pts:1338590 pts_time:14.8732 dts:1338590 dts_time:14.8732 duration:1200 duration_time:0.0133333 stream_index:0
in: pts:1342190 pts_time:14.9132 dts:1342190 dts_time:14.9132 duration:1200 duration_time:0.0133333 stream_index:0
out: pts:1342190 pts_time:14.9132 dts:1342190 dts_time:14.9132 duration:1200 duration_time:0.0133333 stream_index:0
in: pts:1344620 pts_time:14.9402 dts:1344620 dts_time:14.9402 duration:1200 duration_time:0.0133333 stream_index:0
out: pts:1344620 pts_time:14.9402 dts:1344620 dts_time:14.9402 duration:1200 duration_time:0.0133333 stream_index:0
in: pts:1347590 pts_time:14.9732 dts:1347590 dts_time:14.9732 duration:1200 duration_time:0.0133333 stream_index:0
out: pts:1347590 pts_time:14.9732 dts:1347590 dts_time:14.9732 duration:1200 duration_time:0.0133333 stream_index:0
in: pts:1350560 pts_time:15.0062 dts:1350560 dts_time:15.0062 duration:1200 duration_time:0.0133333 stream_index:0
out: pts:1350560 pts_time:15.0062 dts:1350560 dts_time:15.0062 duration:1200 duration_time:0.0133333 stream_index:0
```

The header of the example I found says:

```bash
"Accept-Ranges": "bytes"                 // Helps Chrome
  ```

Maybe work.

I will test.

Thank you so much!!

**Comment by horgh** [comment]
That is interesting that it works well in Firefox but not Chrome.

If that header ends up fixing it in Chrome for you, please let me know and I'll commit it (or if you want to submit a patch that's cool too!).

Thanks for debugging this!

**Comment by juvasquezg** [comment]
Hi @horgh 

Not work in Chrome, maybe need add javascript for the video. The service is good, the client (Chrome) stop.

Thank you so much for your help.

**Comment by horgh** [comment]
Hi @juvasquezg. Sorry for the delay getting back to you.

I've tried using your feed in Chromium 58 and Chrome 58. Both seem to work fine and I don't see the video stop.

All I am doing is opening videostreamer and then going to `file:///home/will/code/go/src/github.com/horgh/videostreamer/index.html` in the browser. I am connecting one client at a time.

I wonder if there is anything else I might be able to do to reproduce the problem that I might be missing. It's difficult to say whether any changes I make will help otherwise. Sorry about that!

**Comment by horgh** [comment]
I made a branch called `lag-issues` where I tried to set the options you showed in the gists/javascript code. As mentioned in the commit message, I was able to set all except 2 of them (I think!).

Could you please try that branch out and see if it improves anything for you?

There are some improvements to be made to this change if they do help you (I noticed TODOs), so there will be more work to do, but it's a start.

Thanks for your help with this.

**Comment by juvasquezg** [comment]
Hi @horgh 

The problem is that I'm using Chrome Version 55.0.2883.95 (64-bit), I updated to Chrome 58 and the client (Chrome 58) does not stop. 

Now I can see the video with master branch and without lag. I will try lag-issues branch.

Thank you so much.

**Comment by horgh** [comment]
Oh, that's great news that the issue went away!

You probably don't need to bother trying the branch then. If the newer Chrome solved the problem, then there's no need for those changes. I won't merge them in in that case.

**Comment by juvasquezg** [comment]
Hi @horgh 

Perfect, Thank you!!! Closed
