### ISSUE TITLE
videostreamer.c:29:2: warning: ‘av_register_all’ is deprecated

### ISSUE THREAD

**Issue by andreas-lenze** [horgh/videostreamer#21]
Hi, building on current, up-to-date OctoPi version.  Just followed the instructions for Videostreamer, get this deprecated error:

**pi@octopi:~ $** go get github.com/horgh/videostreamer
github.com/horgh/videostreamer
videostreamer.c: In function ‘vs_setup’:
videostreamer.c:29:2: warning: ‘av_register_all’ is deprecated [-Wdeprecated-declarations]
  av_register_all();
  ^~~~~~~~~~~~~~~
In file included from /usr/include/arm-linux-gnueabihf/libavdevice/avdevice.h:51,
                 from videostreamer.c:12:
/usr/include/arm-linux-gnueabihf/libavformat/avformat.h:2043:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
**pi@octopi:~ $**

**Comment by horgh** [comment]
Hmm, did it still build though? I think that's just a warning. I'm not sure what the updated API call to use is.

**Comment by andreas-lenze** [comment]
OMG, my bad, terribly sorry; it did indeed build. The message was just a warning. What was I thinking at 3:45 AM??
