### ISSUE TITLE
cannot get any output to browser.

### ISSUE THREAD

**Issue by etamminga** [horgh/videostreamer#9]
Hello,

I've just tried your project. Looking exactly for something like this.

Code compiles and starts just fine. Used cmd line 
./videostreamer -port 9100 -input rtsp://videostreamer:password@172.18.1.10:554/cam/realmonitor?channel=1\&subtype=1 -host 192.168.0.20 -verbose -fcgi=false

It outputs:

2018/07/23 21:29:46 Starting to serve requests on 192.168.0.20:9100 (HTTP)
2018/07/23 21:29:46 encoder: Waiting for clients...

Opening the index.html sample page (with corrected video url) it shows nothing.

2018/07/23 21:29:56 Serving [GET] request from [192.168.0.106:50383] to path [/stream] (0 bytes)
2018/07/23 21:29:56 encoder: New client unable to open input
2018/07/23 21:29:56 Unable to open input
2018/07/23 21:29:56 encoder: Unable to open input
2018/07/23 21:29:56 192.168.0.106:50383: Read error: EOF
2018/07/23 21:29:56 192.168.0.106:50383: Client cleaned up

Tried the remux-example to save the video to file and that works just fine.

Any tips on how to troubleshoot?

Regards,
Erik

**Comment by horgh** [comment]
It's complaining that it can't connect to your camera. Strange that it works with `remux_example` but not with `videostreamer`. They should be opening it the same way.

One idea is that you may need to quote the argument you're giving with the URL since it has '&' in it.

I'll see if there's a way to get more information about the failure.

**Comment by horgh** [comment]
I pushed an update that should give a little more information about why the input can't be opened. Would you be able to try that please?

**Comment by etamminga** [comment]
Thanks for the quick response.

With the latest source I get the following output:
$ ./videostreamer -port 9100 -input "rtsp://videostreamer:VideoStreamer@172.17.10.21:554/cam/realmonitor?channel=1&subtype=1" -host 192.168.0.32 -verbose -fcgi=false
2018/07/24 21:11:18 Starting to serve requests on 192.168.0.20:9100 (HTTP)
2018/07/24 21:11:18 encoder: Waiting for clients...
2018/07/24 21:11:27 Serving [GET] request from [192.168.0.106:51523] to path [/stream] (0 bytes)
2018/07/24 21:11:27 **encoder: New client
unable to open input: No such process**
2018/07/24 21:11:27 encoder: Unable to open input
2018/07/24 21:11:27 192.168.0.106:51523: Read error: EOF
2018/07/24 21:11:27 192.168.0.106:51523: Client cleaned up

Regards,
Erik

**Comment by horgh** [comment]
Weird!

When you tested with `remux_example`, was that on the same machine with the same ffmpeg?

Oh, I think I see. If you add `-format rtsp`, does that work? For some reason it's not the default... I'm not recalling why right now!

**Comment by etamminga** [comment]
Yes, the remux_example was on the same machine with the same ffmpeg

I'll try the -format argument tonight

**Comment by etamminga** [comment]
Eureka! That did it! 

Commandline that worked:

`./videostreamer -port 9100 -input "rtsp://videostreamer:VideoStreamer@172.17.10.21:554/cam/realmonitor?channel=1&subtype=1" -host 192.168.0.32 -verbose -fcgi=false -format=rtsp`

(This is on a Dahua bullet cam, Raspberry Pi3, Debian Stretch)

Thanks for the support!

One step closer to my wall mounted HA display with cam feed.

**Comment by horgh** [comment]
Great! Sounds like a cool project.
